---
- name: Load OS-variable files.
  include_vars: "{{ item }}"
  with_first_found:
    - "defaults/apache_{{ ansible_os_family }}.yml"
    - defaults/apache_default.yml

- name: Ensure Apache is installed.
  package:
    name: "{{ apache_package }}"
    state: present

- name: Copy hello world index.
  copy:
    src: files/index.html
    dest: "/var/www/html/index.html"
  notify: restart apache

- name: Copy test config file.
  copy:
    src: files/test.conf
    dest: "{{ apache_config_dir }}/test.conf"
  notify: restart apache

- name: Ensure Apache is running and starts at boot.
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
