---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/api_key.yml

  tasks:
    - name: Echo the API key which was injected into the env.
      shell: echo $API_KEY
      environment:
        API_KEY: "{{ fake_api_key }}"
      register: echo_result
      changed_when: false

    - name: Show the result.
      debug: var=echo_result.stdout

# api_key is encrypted with pass "test"
